export enum BoardPermission {
	BOARD_READ = "BOARD_READ",
	BOARD_UPDATE = "BOARD_UPDATE",
	BOARD_ARCHIVE = "BOARD_ARCHIVE",
	BOARD_RESTORE = "BOARD_RESTORE",
	BOARD_TRANSFER_OWNERSHIP = "BOARD_TRANSFER_OWNERSHIP",
	INVITATION_READ = "INVITATION_READ",
	MEMBER_INVITE = "MEMBER_INVITE",
	MEMBER_ROLE_UPDATE = "MEMBER_ROLE_UPDATE",
	MEMBER_REMOVE = "MEMBER_REMOVE",
	COLUMN_CREATE = "COLUMN_CREATE",
	COLUMN_UPDATE = "COLUMN_UPDATE",
	COLUMN_DELETE = "COLUMN_DELETE",
	TASK_CREATE = "TASK_CREATE",
	TASK_UPDATE = "TASK_UPDATE",
	TASK_MOVE = "TASK_MOVE",
	TASK_DELETE = "TASK_DELETE",
	AI_RUN = "AI_RUN",
	ACTIVITY_READ = "ACTIVITY_READ",
}

export type BoardPermissionRequirement = readonly [
	BoardPermission,
	...BoardPermission[],
];
